name: "Verify Linked Task"

on: [pull_request]

# For details refer to https://github.com/tim-actions/commit-message-checker-with-regex
jobs:
  check_pr:
    uses: datatrails/avid-global-terraform/.github/workflows/verify-azure-issue.yml@main
    
